### ISSUE TITLE
unsupport ruby 2.3.0

### ISSUE THREAD

**Issue by lolychee** [matt-harvey/git_curate#7]
```
/Library/Ruby/Gems/2.3.0/gems/git_curate-0.6.3/lib/git_curate/branch.rb:17:in `current?': undefined method `match?' for /^\*\s+/:Regexp (NoMethodError)
Did you mean?  match
	from /Library/Ruby/Gems/2.3.0/gems/git_curate-0.6.3/lib/git_curate/runner.rb:26:in `reject!'
	from /Library/Ruby/Gems/2.3.0/gems/git_curate-0.6.3/lib/git_curate/runner.rb:26:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/git_curate-0.6.3/exe/git-curate:10:in `main'
	from /Library/Ruby/Gems/2.3.0/gems/git_curate-0.6.3/exe/git-curate:17:in `<top (required)>'
	from /usr/local/bin/git-curate:22:in `load'
	from /usr/local/bin/git-curate:22:in `<main>'
```

**Comment by matt-harvey** [comment]
Thanks for raising this.

Fixed on [v0.6.4](https://rubygems.org/gems/git_curate/versions/0.6.4).
